### ISSUE TITLE
Publish to PyPi add release manually

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/tap-messagebird#5]

**Comment by edgarrmondragon** [comment]
Wonder if we could try https://github.com/MeltanoLabs/Meta/issues/22 for this repo

**Comment by visch** [comment]
Yeah no problem at all, probably a good idea!

@edgarrmondragon  the MeltanoLabs account has ownership access to `tap-messagebird` on PyPi 

Going to close this as technically we're up and running but automating this wouldn't be a bad idea 


https://pypi.org/project/tap-messagebird/
